Collections
OleksandrIvanovTheBest/Essential pull request #16
Opened 2019-08-17 19:16 UTC by OleksandrZheleznyi

2019-08-17 22:11 UTC, OleksandrIvanovTheBest approved these changes

2019-08-17 22:11 UTC, OleksandrIvanovTheBest commented on Collections/1/MyList.cs
> +        private T[] _value = null;
values

2019-08-17 22:11 UTC, OleksandrIvanovTheBest commented on Collections/2/MyDictionary.cs
> +            return ((IEnumerable<KeyValuePair<TKey, TValue>>)_keyValuePairs).GetEnumerator();
It's OK

2019-08-17 22:11 UTC, OleksandrIvanovTheBest commented on Collections/2/MyDictionary.cs
> +        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
Remove this comented text

2019-08-17 22:13 UTC, OleksandrIvanovTheBest requested changes
Where is an additional task?

2019-08-18 08:43 UTC, OleksandrZheleznyi commented
Where is an additional task? - additional task in Program.cs in the end of file - #4(small function)

2019-08-18 08:52 UTC, OleksandrIvanovTheBest approved these changes

2019-08-18 09:31 UTC, merged